(ns rosalind.problems.rna-test
  (:require
   [clojure.test :refer [deftest testing is]]
   [rosalind.problems.rna :refer [solve-rna]]))


(deftest solve-dna-test
  (testing "solve-rna-sample-test"
    (let [sample (slurp "resources/inputs/rosalind_rna_sample.txt")
          expected "GAUGGAACUUGACUACGUAAAUU"]
      (is (= expected
             (solve-rna sample)))))

  (testing "solve-rna-test"
    (let [data (slurp "resources/inputs/rosalind_rna.txt")
          expected "CACAACGAUGGCAUGCCCGACUACAGUUAUCGGUGACCAAGGACCACCAGACCGAUCUAUGUACGCCCACUAUUUUGCAUCUCGUGACUACCUUGUCAAACCGCAGAUCUUUGCUACUUGGGGAGUACAGGGUCUCUGGGACGUUUAAUGCCCCCGCAAAGUGUUCAGCUUGUGUAAGAUGUGUCCAGUUGCAAGGAUCCGCAUUUAAGAUUGUUGACCAGGGUGUUGAUCGAUGUCUGUCUGGAUUAGAUAGAAACGUUUUCCCUAAUCAGUCCCUGCUCUUACAUGAGUAGCCCGGGAUUAAUAGAUGCCCCACUAAUGUUUCUCGGAUUCGGAAGAGAUCAGGCUGAUCAGUGGCCCUACUAUUUACGUCGCUCUUCAGUUGGCAAAAGAUGUACUAUUAGGUGAGGCUCAGCAAGUUGGGAUGGAGAUUGAACGUGCAAGCGUGUCCACGCUGAAUUGCUCGUGUGCCGUUGCAGGCCUUGGGCCCAGGAAUCCUGGGAGGGGCCGUUAUAUGCGCAGCUUACGGGUCUAUCGCUGUUCGUGGACAAUUCUUUAUCAUCAGGGGGCGAUACUACGGUUCCCCGGCAAUCGUACUUUUCAAAAAUGCGGGAGUCUAAUCAAUGCUGUAUUUACGCCACAGCUCAGUAAUAUCAUACCAUAGUGGAUACAUAGUAACGGUCGAGCUGAUGAUCUGAUGCAUAUCCCAUAGUCCUCCUUUCUUUAAUACGAUAACCGAGGUCUGUAUCCAACUAUGAGAGGCGUUUGGCAUUAACGUCCGACGGCCACCAGCGCGGGAACCGAGAUUAGUUGUAUGUCGUAAAAGGGCGUAAUAUAGGACAACUGUCAACUGGCAUCGCUGCGCUGAAUUGUUUGGACGAGUGGAGUACUAGGAUGGCUCCACGUUCUACUCAGGCAAGAAACGCGGUUCAAAAGGAGCGAGUGUGUUCGGUU"]
      (is (= expected
             (solve-rna data))))))